### ISSUE TITLE
Pattern "**/*" Raises Folders Error

### ISSUE THREAD

**Issue by tajmone** [jurosh/nodejs-eol-converter-cli#1]
First of all, thanks for this really great tool — immensely useful!

I'm facing a problem (using Win 10 x64, Node v9.5.0).

When I want to fix EOLs in all files, including subfolders I use:

    eolConverter crlf "**/*"

because if I use the `"**/*.*"` pattern, it will miss extensionless files (eg: `LICENCE`). But the problem with the `"**/*"` pattern is that eolConverter will also try to fix EOLs in folders, and for each folder raises errors like the following:

```
{ Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:693:18)
    at tryReadSync (fs.js:557:20)
    at Object.fs.readFileSync (fs.js:600:19)
[..etc..]
```

This error doesn't alt the execution, so at the end all files get processed; but I think that eolConverter should check if the file being processed is actually a folder, and skip it.

This fix would allow working with `"**/*"` catch-all patterns without these undue errors.

**Comment by jurosh** [comment]
Thanks, I am happy that this small utility is useful 😊 and thanks for report.

Looks like fix might be pretty easy - probably would be enough adding folder check in try/catch. Would you like to try make PR ?

**Comment by tajmone** [comment]
> Would you like to try make PR ?

I'm not all that versed in Node/JS. Most likely I could handle fixing this, but lack of practical experience might induce me to overlook some issues (especially on cross platform behavior)

But mainly, my PC just crashed a few days ago (thanks to Win 10 mandatory updates that break drivers) so I've just reinstalled my system from scratch and don't have yet all my working tools up and running again — but eolConverter  was one of the top-priority tools in my restore TODOs list.

**Comment by jurosh** [comment]
It was actually pretty easy fix, only glob modification. Fixed in version `1.0.8`

**Comment by tajmone** [comment]
Thanks a lot @jurosh !

Sorry if I didn't take a go at trying to implement it myself, but as mentioned above I don't have experience with Node.JS coding, and I wouldn't have a clear picture on the extensions environment.

**Comment by jurosh** [comment]
It's never late to try that. It isn't hard and code review process by other devs (here me) might give you valuable feedback how to improve.. :)
